name: CI

on: [push, pull_request]

jobs:
    codestyle:
        runs-on: ubuntu-latest
        container: "nofutur3/php-tests:7.4"
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Install dependencies
              run: composer install  --no-interaction

            - name: Chesk code style
              run: vendor/bin/php-cs-fixer fix --dry-run --no-interaction

    laravel7:
        runs-on: ubuntu-latest
        container: "nofutur3/php-tests:7.4"
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Install dependencies
              run: |
                composer install --no-interaction
                composer update illuminate/contracts:^7.0 --no-interaction

            - name: Run static analysis
              run: vendor/bin/phpstan analyse

    laravel8:
        runs-on: ubuntu-latest
        container: "nofutur3/php-tests:7.4"
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Install dependencies
              run: |
                composer install --no-interaction
                composer update illuminate/contracts:^8.0 --no-interaction

            - name: Run static analysis
              run: vendor/bin/phpstan analyse